export const FAV_LIST_REQUEST = "FAV_LIST_REQUEST";
export const FAV_LIST_SUCCESS = "FAV_LIST_SUCCESS";
export const FAV_LIST_FAIL = "FAV_LIST_FAIL";

export const FAV_ADD_REQUEST = "FAV_ADD_REQUEST";
export const FAV_ADD_SUCCESS = "FAV_ADD_SUCCESS";
export const FAV_ADD_FAIL = "FAV_ADD_FAIL";

export const FAV_DELETE_REQUEST = "FAV_DELETE_REQUEST";
export const FAV_DELETE_SUCCESS = "FAV_DELETE_SUCCESS";
export const FAV_DELETE_FAIL = "FAV_DELETE_FAIL";

export const FAV_CLEAR_ACTION = "FAV_CLEAR_ACTION";
