export const LOAD_FAV_LIST_SUCCESS = "LOAD_FAV_LIST_SUCCESS";
export const ADD_FAV_SUCCESS = "FAV_ADD_SUCCESS";
export const DELETE_FAV_OPTIMISTIC = "DELETE_FAV_OPTIMISTIC";
export const FAV_CLEAR_ACTION = "FAV_CLEAR_ACTION";
