export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const LOAD_ORDERS_SUCCESS = "LOAD_USER_ORDERS_SUCCESS";
export const LOAD_ORDER_BY_ID_SUCCESS = "LOAD_ORDER_BY_ID";
export const UPDATE_ORDER_STATUS_OPTIMISTIC = 'UPDATE_ORDER_STATUS_OPTIMISTIC' 
